### ISSUE TITLE
Secondary windows are not showing anything

### ISSUE THREAD

**Issue by DPoSign** [ColossusFX/PoloniexAutoTrader#1]
Visual Studio Community 2017

### Description
![image](https://user-images.githubusercontent.com/13325923/27734353-629b29dc-5d92-11e7-80d1-352ec3a1689c.png)
Hello, I'm testing your project right now. I can not get the information in these windows (see image).
Your project is great by the way :)
### Steps to recreate
I clone PoloniexApi.Net, added references, the project built, runs perfectly, I launched one strategy to get this result.

**Comment by DPoSign** [comment]
Nevermind, it works! Sorry for the false alert

**Comment by ColossusFX** [comment]
The timer works datetime.now + market period

I need to write some bits so 15min starts on the 15/30/45/00 etc

There are lots of small things to do still

**Comment by ColossusFX** [comment]
Re: Percentage Change algo

The version on github will trade every tick of price changes from market period by (x) %

I have a version (yet to test and upload) which will only trades OnBar (Market Period) when tick price changes.

So please read and understand code before using larger trade sizes!!

**Comment by DPoSign** [comment]
I understand the risk and I trust what you did I'll let you know if the program has an anomalous behaviour ;)

**Comment by ColossusFX** [comment]
Thanks for testing.
There WILL be issues, I will try to continue to work on this when I have time.
To be safe while testing to get stats, untick buy & sell, you still get info.
Polo API has many issues, which really limits you which is annoying.

Using range trader with buy only is a good option.

% Trader needs some work, it's in testing phase.

Range break can buy the tops, use only if you have a hunch on potential breakout

If you would like to join our slack, I will send an invite over.

**Comment by DPoSign** [comment]
Yes send me an invitation. daniel.poinsignon[a]gmail.com

**Comment by ColossusFX** [comment]
when you get on I will invite you to private channels :)
